/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMenuUtama;
import java.awt.event.ActionListener;

/**
 *
 * @author habib
 */
public class MenuAsisten extends javax.swing.JFrame {

    /**
     * Creates new form MenuAsisten
     */
    public MenuAsisten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tambahTubes = new javax.swing.JButton();
        tambahMahasiswa = new javax.swing.JButton();
        kurangMahasiswa = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ASISTEN");

        tambahTubes.setText("TAMBAH TUBES");
        tambahTubes.setToolTipText("");
        tambahTubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTubesActionPerformed(evt);
            }
        });

        tambahMahasiswa.setText("TAMBAH MAHASISWA");

        kurangMahasiswa.setText("KURANG MAHASISWA");

        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(tambahTubes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kurangMahasiswa)
                                    .addComponent(tambahMahasiswa))))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kembali)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(tambahTubes)
                .addGap(18, 18, 18)
                .addComponent(tambahMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(kurangMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(kembali)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahTubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTubesActionPerformed
        // TODO add your handling code here:
        Controller.ControllerMenuUtama cl=new ControllerMenuUtama();
        this.dispose();
    }//GEN-LAST:event_tambahTubesActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton kurangMahasiswa;
    private javax.swing.JButton tambahMahasiswa;
    private javax.swing.JButton tambahTubes;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the kembali
     */
    public Object getKembali() {
        return kembali;
    }

    public Object getKurangMahasiswa() {
        return kurangMahasiswa;
    }

    public Object getTambahMahasiswa() {
        return tambahMahasiswa;
    }

    public Object getTambahTubes() {
        return tambahTubes;
    }
    public void addListener(ActionListener e){
        
    }
}
