/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMenuUtama;
import java.awt.event.ActionListener;

/**
 *
 * @author habib
 */
public class MenuAsisten extends javax.swing.JFrame implements View {

    /**
     * Creates new form MenuAsisten
     */
    public MenuAsisten() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tambahTubes = new javax.swing.JButton();
        tambahMahasiswa = new javax.swing.JButton();
        kurangMahasiswa = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tampilkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ASISTEN");

        tambahTubes.setText("TAMBAH TUBES");
        tambahTubes.setToolTipText("");
        tambahTubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTubesActionPerformed(evt);
            }
        });

        tambahMahasiswa.setText("TAMBAH MAHASISWA");

        kurangMahasiswa.setText("KURANG MAHASISWA");

        keluar.setText("Logout");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        tampilkan.setText("Tampilkan TUBES & Mahasiswa");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tampilkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kurangMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambahMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambahTubes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keluar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(tambahTubes)
                .addGap(18, 18, 18)
                .addComponent(tambahMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(kurangMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(tampilkan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(keluar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahTubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTubesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahTubesActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilkanActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kurangMahasiswa;
    private javax.swing.JButton tambahMahasiswa;
    private javax.swing.JButton tambahTubes;
    private javax.swing.JButton tampilkan;
    // End of variables declaration//GEN-END:variables

 
    public Object getKeluar() {
        return keluar;
    }

    public Object getKurangMahasiswa() {
        return kurangMahasiswa;
    }

    public Object getTambahMahasiswa() {
        return tambahMahasiswa;
    }

    public Object getTambahTubes() {
        return tambahTubes;
    }
    public javax.swing.JButton getTampilkan() {
        return tampilkan;
    }
    @Override
    public void addActionListener(ActionListener e) {
        keluar.addActionListener(e);
        kurangMahasiswa.addActionListener(e);
        tambahMahasiswa.addActionListener(e);
        tambahTubes.addActionListener(e);
        tampilkan.addActionListener(e);
    }

    
}
